/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Option,
} from './components/carbonic-dropdown/interfaces';


export namespace Components {

  interface CarbonicDropdown {
    /**
    * Option that is shown as selected one.
    */
    'chosenOption': Option;
    'isExpanded': boolean;
    /**
    * Callback that will be called on every chosen option change
    */
    'onChangeHandler': Function;
    /**
    * List of selectable options that dropdown contains.
    */
    'options': Option[];
  }
  interface CarbonicDropdownAttributes extends StencilHTMLAttributes {
    /**
    * Option that is shown as selected one.
    */
    'chosenOption'?: Option;
    'isExpanded'?: boolean;
    /**
    * Event emitted on every option change
    */
    'onCarbonicDropdownValueChanged'?: (event: CustomEvent) => void;
    /**
    * Callback that will be called on every chosen option change
    */
    'onChangeHandler'?: Function;
    /**
    * List of selectable options that dropdown contains.
    */
    'options'?: Option[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'CarbonicDropdown': Components.CarbonicDropdown;
  }

  interface StencilIntrinsicElements {
    'carbonic-dropdown': Components.CarbonicDropdownAttributes;
  }


  interface HTMLCarbonicDropdownElement extends Components.CarbonicDropdown, HTMLStencilElement {}
  var HTMLCarbonicDropdownElement: {
    prototype: HTMLCarbonicDropdownElement;
    new (): HTMLCarbonicDropdownElement;
  };

  interface HTMLElementTagNameMap {
    'carbonic-dropdown': HTMLCarbonicDropdownElement
  }

  interface ElementTagNameMap {
    'carbonic-dropdown': HTMLCarbonicDropdownElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
